# Generated by Django 2.0.7 on 2018-07-23 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited', models.IntegerField()),
                ('status', models.BooleanField()),
                ('first_date', models.DateField()),
                ('last_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceDataLive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(auto_now_add=True)),
                ('counts', models.IntegerField(default=0)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('firstset', models.DateField()),
                ('password', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('units', models.IntegerField()),
                ('counts', models.IntegerField()),
                ('mobilephone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ShopDataLive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField(auto_now_add=True)),
                ('last', models.DateTimeField(auto_now=True)),
                ('visited', models.IntegerField(default=0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(auto_now_add=True)),
                ('counts', models.IntegerField(default=0)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='devicedatalive',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.ShopDataLive'),
        ),
        migrations.AddField(
            model_name='device',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Shop'),
        ),
    ]
