# Generated by Django 2.1 on 2018-10-26 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('sums', models.IntegerField(default=0)),
                ('pin1', models.IntegerField(default=0)),
                ('pin2', models.IntegerField(default=0)),
                ('pin3', models.IntegerField(default=0)),
                ('pin4', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShopDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('sums', models.IntegerField(default=0)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='pin1_sum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='pin2_sum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='pin3_sum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='pin4_sum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicedaily',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Device'),
        ),
    ]
